### ISSUE TITLE
Criar método buscar(Fornecedor) - EntradaDAO

### ISSUE THREAD

**Issue by lucasljf** [lucasljf/erp#22]
De acordo com o diagrama de classes e no pacote `dao`. Observe os tipos (e ordem) dos parâmetros e retorno.

**Comment by kralluz** [comment]
opa

**Comment by kralluz** [comment]
eu

**Comment by crzcarl0s** [comment]
.

**Comment by crzcarl0s** [comment]
(era so um teste de conceito professor)
