### ISSUE TITLE
Criar método salvar(Saida) - SaidaDAO

### ISSUE THREAD

**Issue by lucasljf** [lucasljf/erp#33]
De acordo com o diagrama de classes e no pacote `dao`. Observe os tipos (e ordem) dos parâmetros e retorno.

**Comment by Emiliano-Souza** [comment]
eu

**Comment by hugosymon** [comment]
eu

**Comment by cmarialaura** [comment]
eu

**Comment by lucasljf** [comment]
Data final para conclusão da issue: 10/04.
