### ISSUE TITLE
Criar método alterarStatus(Saida) - SaidaDAO

### ISSUE THREAD

**Issue by lucasljf** [lucasljf/erp#34]
De acordo com o diagrama de classes e no pacote `dao`. Observe os tipos (e ordem) dos parâmetros e retorno.

**Comment by YAN-Ks** [comment]
Opa

**Comment by joy-c1** [comment]
eu

**Comment by italo-gs** [comment]
eu

**Comment by lucasljf** [comment]
Data final para conclusão da issue: 10/04.
