### ISSUE TITLE
Criação da classe Saida

### ISSUE THREAD

**Issue by lucasljf** [lucasljf/erp#4]
De acordo com o diagrama de classes e no pacote `modelo`.

**Comment by joy-c1** [comment]
Eu

**Comment by joy-c1** [comment]
Professor, só pra ter certeza, nessa classe a gente cria os atributos, getters e setters? Precisa de construtor também?

**Comment by lucasljf** [comment]
Acredito que o ideal seja seguir o diagrama. Implementar apenas os atributos e métodos que estão presentes na imagem.

**Comment by lucasljf** [comment]
Não é preciso implementar métodos que persistam dados no banco.
