### ISSUE TITLE
Popular com 100 registros a tabela tb_produto

### ISSUE THREAD

**Issue by lucasljf** [lucasljf/erp#44]
Utilizando como referência o diagrama do banco e o arquivo banco.sql. Edite o arquivo inserts.sql adicionando a quantidade solicitada de comandos INSERT que preenchem os campos. Esses comandos serão muito úteis para testes.

**Comment by VictorNix** [comment]
Professor eu estou com dificuldade para colocar o código no git desktop, não estou achado o local para colocar o código.

**Comment by lucasljf** [comment]
Leve tudo pronto para a próxima aula que lhe oriento.
