### ISSUE TITLE
Criação da classe Produto

### ISSUE THREAD

**Issue by lucasljf** [lucasljf/erp#6]
De acordo com o diagrama de classes e no pacote `modelo`. Atenção: é uma classe abstrata.

**Comment by GuiAlencar** [comment]
eu

**Comment by GuiAlencar** [comment]
Professor, poderia me informar onde o senhor disponibilizou o diagrama de classe

**Comment by lucasljf** [comment]
> eu

Para as próximas issues, aguarde que eu mesmo atribuirei um responsável.

> Professor, poderia me informar onde o senhor disponibilizou o diagrama de classe

Acabei de adicionar na pasta `documentos`.

**Comment by lucasljf** [comment]
Não é preciso implementar métodos que persistam dados no banco.

**Comment by GuiAlencar** [comment]
professor, criei a classe produto e já fiz o commit na minha branch pedindo pull requests

**Comment by lucasljf** [comment]
Vi que fez o commit, só falta criar o pull request.
