### ISSUE TITLE
Criar teste para método buscar(Fornecedor) - EntradaDAO

### ISSUE THREAD

**Issue by lucasljf** [lucasljf/erp#75]
Implementar um teste unitário para o método indicado. Crie quantos `asserts` foram necessários.

**Comment by kralluz** [comment]
eu

**Comment by kralluz** [comment]
Acredito que uma **nova Issue** relacionada a classe mercadoria, ao criar a tela de mercadoria notei a necessidade de uma propriedade chamada código de barras que é do tipo String e tem a **quantidade fixa de 13 caracteres**, minha justificativa para esta adição é que os códigos de barras EAN-13 / GTIN-13 são chamados de códigos de barras para produtos e identificam o produto nos Pontos de Vendas de supermercados e lojas todos os produtos, como alimentos, roupas etc.

**Comment by kralluz** [comment]
tambem foi encontrado a necessidade de mais uma propriedade na da classe mercadoria, chamada dataDeValidade que deve ser do tipo date, onde receberá a data de validade do produto em questão, consequentemente, uma coluna na tabela produto, uma sujestão seria a separação da tabela produto, em outras 2 tabelas, chamadas mercadoria e serviço.
