### ISSUE TITLE
Criação do diagrama do banco de dados

### ISSUE THREAD

**Issue by lucasljf** [lucasljf/erp#8]
Modelar o banco de dados. Subir para o repositório o arquivo do diagrama e uma imagem do diagrama (png). Pode ser utilizado o MySQL Workbench / PlantUML / BR Modelo ou outra ferramenta. Sugiro que **duas pessoas** fiquem responsáveis por essa tarefa. Deve ser concluída até a próxima aula.

**Comment by yaszsz** [comment]
Eu

**Comment by joy-c1** [comment]
eu

**Comment by lucasljf** [comment]
Por enquanto, vamos tentar manter apenas uma issue por contribuidor.
@joy-c1 já concluiu a primeira...

**Comment by lucasljf** [comment]
Como finalizou sua primeira tarefa, @yaszsz agora, sim, responsável por essa.
Sugiro discutirem bem os campos e tipos de dados.
Quanto antes concluírem, melhor.

**Comment by joy-c1** [comment]
Professor, na classe Entrada não deveria ter o campo ''tipoEntrada", assim como na de Saída tem o "tipoSaída"?

**Comment by lucasljf** [comment]
> Professor, na classe Entrada não deveria ter o campo ''tipoEntrada", assim como na de Saída tem o "tipoSaída"? 

Pelo que foi discutido em sala, não. Todas as entradas possuem a mesma origem (tipo). 

Futuramente podemos fazer essa alteração, caso necessário.
